AllCops:
  Exclude:
    - 'db/**/**'
    - 'config/**/**'
    - 'bin/**/**'
    - 'test/**/**' # temporary
Style/Documentation:
  Exclude:
    - 'app/helpers/**'
    - 'app/mailers/**'
    - 'app/models/application_record.rb'
Style/DateTime:
  Enabled: false
