version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
